apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-ssd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stresstest
  namespace: default
spec:
  completions: 1
  parallelism: 1
  activeDeadlineSeconds: 3600  # Set a timeout of 60 minutes
  template:
    metadata:
      labels:
        app: stresstest
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/compute-class: "Balanced"
      volumes:
        - name: unity-volume
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: unity-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "ssd"
                resources:
                  requests:
                    storage: 50Gi
      containers:
        - name: stresstest
          image: us-central1-docker.pkg.dev/unity-solutions-devops-test/docker-repository/stresstest:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/unityproject"
              name: unity-volume
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 10Gi
              memory: 4Gi
            requests:
              cpu: "2"
              ephemeral-storage: 10Gi
              memory: 4Gi
          env:
            - name: SERVER_IP
              value: 35.228.225.227
            - name: SERIAL
              valueFrom:
                secretKeyRef:
                  name: unity-license
                  key: SERIAL
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: unity-license
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unity-license
                  key: PASSWORD
